# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greet.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgreet.proto\x12\rproductUpdate\"E\n\x14ProductUpdateRequest\x12-\n\rproductUpdate\x18\x01 \x03(\x0b\x32\x16.productUpdate.Product\"(\n\x15ProductUpdateResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"`\n\x07Product\x12\x13\n\x0bproductType\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x11\n\tsendPoint\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x0c\n\x04\x64\x61te\x18\x05 \x01(\t2l\n\x0eProductUpdater\x12Z\n\rUpdateProduct\x12#.productUpdate.ProductUpdateRequest\x1a$.productUpdate.ProductUpdateResponseB\x1b\xaa\x02\x18PiecykPolHurt.DataImportb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greet_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\030PiecykPolHurt.DataImport'
  _PRODUCTUPDATEREQUEST._serialized_start=30
  _PRODUCTUPDATEREQUEST._serialized_end=99
  _PRODUCTUPDATERESPONSE._serialized_start=101
  _PRODUCTUPDATERESPONSE._serialized_end=141
  _PRODUCT._serialized_start=143
  _PRODUCT._serialized_end=239
  _PRODUCTUPDATER._serialized_start=241
  _PRODUCTUPDATER._serialized_end=349
# @@protoc_insertion_point(module_scope)
