# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greet.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgreet.proto\x12\rproductUpdate\"b\n\x14ProductUpdateRequest\x12(\n\x04type\x18\x01 \x01(\x0b\x32\x1a.productUpdate.ProductType\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x0e\n\x06\x62ranch\x18\x03 \x01(\t\"(\n\x15ProductUpdateResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x8a\x01\n\x0bProductType\x12<\n\x0bproductType\x18\x01 \x01(\x0e\x32\'.productUpdate.ProductType.PRODUCT_TYPE\"=\n\x0cPRODUCT_TYPE\x12\n\n\x06ORZECH\x10\x00\x12\n\n\x06KOSTKA\x10\x01\x12\x0b\n\x07GROSZEK\x10\x02\x12\x08\n\x04MIAL\x10\x03\x32l\n\x0eProductUpdater\x12Z\n\rUpdateProduct\x12#.productUpdate.ProductUpdateRequest\x1a$.productUpdate.ProductUpdateResponseB\x1b\xaa\x02\x18PiecykPolHurt.DataImportb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greet_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\030PiecykPolHurt.DataImport'
  _PRODUCTUPDATEREQUEST._serialized_start=30
  _PRODUCTUPDATEREQUEST._serialized_end=128
  _PRODUCTUPDATERESPONSE._serialized_start=130
  _PRODUCTUPDATERESPONSE._serialized_end=170
  _PRODUCTTYPE._serialized_start=173
  _PRODUCTTYPE._serialized_end=311
  _PRODUCTTYPE_PRODUCT_TYPE._serialized_start=250
  _PRODUCTTYPE_PRODUCT_TYPE._serialized_end=311
  _PRODUCTUPDATER._serialized_start=313
  _PRODUCTUPDATER._serialized_end=421
# @@protoc_insertion_point(module_scope)
